apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: mafudge
spec:
  source:
    git:
      revision: master
      url: https://github.com/StrongMonkey/demo.git
  template:
    arguments:
      - name: IMAGE
        value: rio-registry.io/daishan1992/demo:v1
      - name: BUILDKIT_DAEMON_ADDRESS
        value: tcp://buildkit
    kind: ClusterBuildTemplate
    name: buildkit
